//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using PotterLib;
using NUnit.Framework;
using System.Collections.Generic;

namespace PotterLibTest
{	
	[TestFixture]
	public class PromotionPackTests
	{
		PromotionPacks promotionPacks;
		int numberOfGroups;

		
		[SetUp]
		public void SetUp()
		{
			promotionPacks = new PromotionPacks();
			numberOfGroups = 0;
		}

		[Test]
		public void AddOneBookCreateOneGroup()
		{
			promotionPacks.AddBook(1);

			int numberOfGroups = promotionPacks.GetNumberOfGroups();
			
			Assert.AreEqual(1, numberOfGroups);
		}

		[Test]
		public void AddTwoBooksCreateOneGroup()
		{
			promotionPacks.AddBook(1);
			promotionPacks.AddBook(2);
			
			numberOfGroups = promotionPacks.GetNumberOfGroups();
			
			Assert.AreEqual(1, numberOfGroups);
		}

		[Test]
		public void AddTwoBooksCreateTwoGroups()
		{
			promotionPacks.AddBook(1);
			promotionPacks.AddBook(1);
			
			numberOfGroups = promotionPacks.GetNumberOfGroups();
			
			Assert.AreEqual(2, numberOfGroups);
		}

		[Test]
		public void AddThreeBooksCreateTwoGroups()
		{
			promotionPacks.AddBook(1);
			promotionPacks.AddBook(1);
			promotionPacks.AddBook(5);
			
			numberOfGroups = promotionPacks.GetNumberOfGroups();
			
			Assert.AreEqual(2, numberOfGroups);
		}
	}
}

